
# REF: https://github.com/asciidoctor/asciidoctor-reducer#reduce-files-in-a-github-repository
name: Reduce README
on:
  push:
    paths:
    - 'docs/README-source.adoc'
    branches: ['**']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Asciidoctor Reducer
      run: sudo gem install asciidoctor-reducer
    - name: Reduce README
      run: asciidoctor-reducer --preserve-conditionals -o docs/README.adoc docs/README-source.adoc
    - name: Commit and Push README
      uses: EndBug/add-and-commit@v9
      with:
        add: 'docs/README.adoc'
